public class Constants {
    public static final Integer WEEK_INTEGER = 7;
    public static final Integer FOUR_WEEK_CYCLE = 4;
    public static final Integer TWELVE_WEEKS_DAYS = 84;
    public static final Integer ONE_WEEK_DAYS = 7;
    public static final Integer TWO_WEEK_DAYS = 14;
    public static final Integer THREE_WEEK_DAYS = 21;
    public static final Integer FOUR_WEEK_DAYS = 28;
    public static final Integer CALL_OFFSET_ONE_DAY = 1;
    public static final Integer CALL_OFFSET_THREE_DAYS = 3;
    public static final String DEFAULT_SM_ROUTE_360_SUBMIT_ORDERS = '360';
}